### ISSUE TITLE
Sgadmer выполнен урок 2

### ISSUE THREAD

**Issue by Sgadmer** [zepster/js-lessons#1]
Здравствуйте, задачи на объекты сделал. У вас будет что-то еще по ним? 
https://github.com/Sgadmer/js-lessons/tree/master/src/object

**Comment by zepster** [comment]
Отлично.

Попробуй сделать следующие задачи:

1.  Удалить ключ из объекта и вернуть новый
 obj1 !== obj2 
```javascript
let obj1 = { name: 'Max' , age: 22 };  
let obj2 = removeKey(obj1, 'name'); 
// obj2 ->  { age: 22 }
```

2. Создать и вернуть объект, ключи которого есть в обоих объектах
Придумай название функции
```javascript
let obj1 = {
  firstName: 'Max',
  lastName: 'Xam',
  age: 22,
};

let obj2 = {
  age: 22,
  city: 'NY',
};

let obj3 = функция(obj1, obj2);
// obj3 -> {  age: 22  }
```
3. Создать и вернуть объект, ключи которого есть только в одном из объектов (разность)
Придумай название функции
```javascript
let obj1 = {
  firstName: 'Max',
  lastName: 'Xam',
  age: 22,
};

let obj2 = {
  age: 22,
  city: 'NY',
};

let obj3 = функция(obj1, obj2);
// obj3 -> {  city: 'NY', lastName: 'Xam',  firstName: 'Max',  }
```

4. По аналогии с https://github.com/Sgadmer/js-lessons/blob/master/tests/object.test.js попробуй создать тесты к своим новым функциям

**Comment by Sgadmer** [comment]
Готово, задачи и тесты в тех же файлах, под заголовком (/*---НОВЫЕ ЗАДАЧИ----)
https://github.com/Sgadmer/js-lessons/tree/master/src/object
https://github.com/Sgadmer/js-lessons/blob/master/tests/object.test.js

**Comment by zepster** [comment]
1. removeKey - ок
2. sameKeysObj. Ошибка.
Сравнивать значения в ключах не нужно. 
```javascript
  if (obj1[key] == obj2[key2])
```
Мы проверяем только ключи объекта.
В цикле достаточно пройти по 1 объекту (подумай почему)
Для проверки можно использовать уже готовую функцию
```javascript
function hasKey(object, key) 
```

3. differentKeysObj. Ошибка.
Так же сравниваешь значения.
```javascript
if (obj2[key] == obj1[key2])
```
У тебя 4 цикла, попробуй сделать за 2

#### Не коммить вывод в консоль внутри функций
```javascript
console.log(obj3);
```
Можешь использовать пока делаешь, но потом удаляй

Тесты пока отложи

**Comment by Sgadmer** [comment]
Исправил 
https://github.com/Sgadmer/js-lessons/blob/master/src/object/index.js

**Comment by zepster** [comment]
👍
