### ISSUE TITLE
Invalid Api key

### ISSUE THREAD

**Issue by Sgadmer** [zepster/js-lessons#10]
Здравствуйте, начал выполнять задания со списком фильмов, но запрос всегда возвращает  Invalid Api key, хотя с  другой ссылкой (на один постер) всё в порядке, в чем здесь проблема?

Ключ по почте активирован,  с ключами с других почт то же самое.

https://github.com/Sgadmer/js-lessons/blob/movies/src/listOfMovies/src/main.js - код

https://github.com/Sgadmer/js-lessons/tree/movies/src/listOfMovies/screenshots - Скриншоты

**Comment by zepster** [comment]
Замени 
```javascript
movieXHR.open('GET', 'http://img.omdbapi.com/?apikey=[586fb65b]&', true);
```
на
```javascript
movieXHR.open('GET', 'http://img.omdbapi.com/?apikey=586fb65b', true);
```

**Comment by Sgadmer** [comment]
Теперь пишет 404

> GET http://img.omdbapi.com/?apikey=586fb65b 404 (Not Found)

**Comment by Sgadmer** [comment]
> Server Error
> 
> 404 - File or directory not found.
> The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

**Comment by zepster** [comment]
пример
```
http://www.omdbapi.com/?apikey=586fb65b&s=start
```
где 
```
http://www.omdbapi.com/?apikey=<твой ключ>&s=<строка из названия фильма>
```

в ответе массив в результатами

http://www.omdbapi.com/ - смотри какие параметры можно передать на поиск **By Search**

**Comment by Sgadmer** [comment]
Спасибо, теперь понял
