### ISSUE TITLE
Как исправить данную ошибку ?

### ISSUE THREAD

**Issue by Roman66fgh** [zepster/js-lessons#12]
![CfBm3n0FsMU](https://user-images.githubusercontent.com/55583561/77150373-cb86a080-6aa4-11ea-82f0-bd839f773467.jpg)
remote: Permission to zepster/js-lessons.git denied to Roman66fgh.
fatal: unable to access 'https://github.com/zepster/js-lessons.git/': The requested URL returned error: 403
P.S Делал в master

**Comment by zepster** [comment]
ты не можешь отправлять изменения в мой репозиторий. для этого ты делал копию (Fork). все изменения отправляй в свой проект https://github.com/Roman66fgh/js-lessons

и скачивай проект тоже от себя 
```
git clone git@github.com:Roman66fgh/js-lessons.git
```

**Comment by Roman66fgh** [comment]
А как добавить SSH-ключ?
