### ISSUE TITLE
не получается запушить в свой репозиторий 

### ISSUE THREAD

**Issue by medoed-666** [zepster/js-lessons#13]
![1](https://user-images.githubusercontent.com/55583230/78383763-fe26b200-75e9-11ea-8b23-5ddbbaa53fab.png)
так получается если просто прописываешь git push или git push origin/master
![2](https://user-images.githubusercontent.com/55583230/78383945-5493f080-75ea-11ea-93ab-85d3a908a1f1.png)
а так через git push <ссылка на свой репозиторий>

**Comment by zepster** [comment]
```
 git push <ссылка на свой репозиторий> 
```
такой команды не существует

Ты сделал копию проекта (fork) с моего репозитория, а скачать его ты должен со своего 
```
git clone <ссылка на свой репозиторий> 
```
Уже в него и пушь свои изменения
```
git push
```

**Comment by medoed-666** [comment]
В том то и дело,что скачал я со своего

**Comment by zepster** [comment]
выполни команду и покажи результат 
```
git remote -v
```

**Comment by medoed-666** [comment]
![image](https://user-images.githubusercontent.com/55583230/78454180-7bfcc300-76a7-11ea-81cb-0f946165ab1f.png)
заново загрузил копию со своего репозиторию, прописал <git remote -v>,но почему-то ссылается на ваш репозиторий,или так и должно?

**Comment by zepster** [comment]
- копия моего репозитория через fork
![1](https://user-images.githubusercontent.com/2792975/78455035-0c89d200-76ad-11ea-9f76-6e1ec4767c6e.png)
- копируешь ссылку уже со своей страницы ```git clone https://github.com/medoed-666/js-lessons.git```

![2](https://user-images.githubusercontent.com/2792975/78455040-0eec2c00-76ad-11ea-8b00-7e57318bd7ca.png)

больше делать ничего не нужно. уже на этом этапе у тебя будет твои ссылки ```git remote -v```
