### ISSUE TITLE
проблема с пушем

### ISSUE THREAD

**Issue by Hiro-Create** [zepster/js-lessons#16]
![Аннотация 2020-04-04 121514](https://user-images.githubusercontent.com/55582999/78422273-24dafc00-766f-11ea-8bdf-92d540dacc35.png)

**Comment by zepster** [comment]
выполни и покажи результат команды 
```
git remote -v
```

**Comment by Hiro-Create** [comment]
![Аннотация 2020-04-04 162128](https://user-images.githubusercontent.com/55582999/78450545-5b753e80-7690-11ea-9437-af4f16915fb6.png)

**Comment by Hiro-Create** [comment]
я так понял я должен свой репозиторий скачивать?

**Comment by zepster** [comment]
Да, скачивай свой и push делай в свой

**Comment by zepster** [comment]
Есть еще проблемы по этой теме? Если нет то закрывай
