### ISSUE TITLE
Проблема с новой веткой 

### ISSUE THREAD

**Issue by fbmys** [zepster/js-lessons#17]
Создал новую ветку и перешел в нее. после изменений попробовал запушить
![image](https://user-images.githubusercontent.com/55583325/78469714-beb8ac80-7734-11ea-83c1-757278dbd49f.png)
Ввел команду из последней строки
![image](https://user-images.githubusercontent.com/55583325/78469721-cd9f5f00-7734-11ea-999c-56aca7c14d39.png)

**Comment by zepster** [comment]
Расскажи как создаешь ветку и покажи результат команды  ```git remote -v```

**Comment by fbmys** [comment]
![image](https://user-images.githubusercontent.com/55583325/78471910-c9c80880-7745-11ea-98fa-e0da5645fd83.png)
Создавал из главной git checkout -b название

**Comment by zepster** [comment]
Пробуй так
```
git push -u origin <НАЗВАНИЕ_ТВОЕЙ_ВЕТКИ>
```
