### ISSUE TITLE
задачи

### ISSUE THREAD

**Issue by Sgadmer** [zepster/js-lessons#2]
Доделал те задачи (все ответы выводятся в консоль) 
https://github.com/Sgadmer/js-practise/tree/master/assets/js

Но не совсем уверен, что правильно сделал " limitCalls "
и " rle ".  
Точнее " rle " по данным из задания работает правильно, но если взять, например, строку ABCABCABCDDDFFFFFF, то как привести ее к виду -9ABCABCABC3D6F не перегружая код, я пока не знаю

**Comment by zepster** [comment]
### limitCalls 
```javascript
function limitCalls(fn, maxCalls) {

  function Func () {
    /**
     * 1 не обязательно делать сверку с числом (посмотри https://learn.javascript.ru/type-conversions как выражение в if будет преобразовано). сделай без оператора сравнения
     * 2 Отметим вызов функции до ее выполнения (возможен вариант, когда функция будет вызвана более n раз до ее выполнения)
     * 
     * limitedLog(); // undefined - как индикатор того, что функция ничего не делает
     */
    if ( // замени условие ) { // 1
      maxCalls--; // 2
      fn();
    }
  }

  return Func;
}
```

### rle
Не ясен вопрос. 
```
ABCABCABCDDDFFFFFF != -9ABCABCABC3D6F 
```
что за пример такой?

### Стиль кода
https://github.com/airbnb/javascript посмотри общие правила форматирования кода для JS. Ты пишешь как попало
