### ISSUE TITLE
Массивы

### ISSUE THREAD

**Issue by Sgadmer** [zepster/js-lessons#5]
Не совсем уверен, что сделал правильно последние 2 задания, но по тестам всё ок.
https://github.com/Sgadmer/js-lessons/blob/master/src/array/index.js

В последних 2 тестах, кажется была небольшая опечатка. Оставил пометки  внутри тестов.
https://github.com/Sgadmer/js-lessons/blob/master/tests/array.test.js

**Comment by zepster** [comment]
Точно! В тесте есть ошибка. Попробуй поправить **только эти** опечатки и прислать пулл реквест, свои выполненные задания в пулл реквест попасть не должны

**Comment by Sgadmer** [comment]
А каким образом можно отправить в пулл реквест только 1 файл? Я не смог найти это в интернете.

**Comment by Sgadmer** [comment]
Целый день устраивал танцы с бубном, а решение было на поверхности...

**Comment by zepster** [comment]
готово
