### ISSUE TITLE
Как получить значение из select?

### ISSUE THREAD

**Issue by Sgadmer** [zepster/js-lessons#8]
Здравствуйте, написал небольшую анимацию, и хочу, чтобы она запускалась через  select, но при попытке взять value из select  через addEventListener получаю ошибку "невозможно взять значение из Null". В интернете предлагают использовать такую схему 

var select = document.getElementById("select_");
var value = select.value;

но у меня не получилось так сделать. Так как получить Value из select? (Пока оставил ввод через input)

2) Как прервать анимацию, которая работает через setInterval? Про это тоже мало полезного нашел

3) Как узнать текущую высоту рабочей/видимой области браузера (т.е. не учитывая различных вкладок сверху)? Я использую clientHeight для ограничения области движения шариков, но они все равно уходят за границы под сохранённые вкладки (фиолетовый шар на скрине) 
https://github.com/Sgadmer/Parallax-test/blob/master/Screenshot_208.png

сам код - https://github.com/Sgadmer/Parallax-test.git

P.S. (Если в инпут быстро вводить 3 и удалять, и делать так много раз, то можно заработать приступ эпилепсии)

**Comment by zepster** [comment]
Для таких вещей можешь создать запрос в своей репе (https://github.com/Sgadmer/Parallax-test/issues) и тегнуть меня там.  Этот вопрос не относится к текущему проекту. Согласен?
